question_data = [
    {"text": "A group of islands is called an 'archipelago'.",
     "answer": "True", },
    {"text": "The Republic of Malta is the smallest microstate worldwide.",
     "answer": "False", },
    {"text": "San Marino is the only country completely surrounded by another country.",
     "answer": "False", },
    {"text": "Ottawa is the capital of Canada.",
     "answer": "True", },
    {"text": "There are no deserts in Europe.",
     "answer": "True", },
    {"text": "California is larger than Japan.",
     "answer": "True", },
    {"text": "Hungary is the only country in the world beginning with H.",
     "answer": "False", },
    {"text": "Rhode Island is actually located on the US mainland, despite its name.",
     "answer": "True", },
    {"text": "There is an island in Japan called kunoshima, A.K.A. 'Rabbit Island', so named because of it's huge population of rabbits.",
        "answer": "True", }]
